[workspace]
authors = ["Elian NEPPEL <elian.dev@posteo.com>"]
channels = ["conda-forge"]
name = "zemesh"
platforms = ["linux-64", "linux-aarch64"]

[activation.env]
RUST_LOG = "debug"
ZENOH_ROUTER_CONFIG_URI = ""
ZENOH_SESSION_CONFIG_URI = ""

[pypi-dependencies]
elian_experiment = { path = ".", editable=true}

[dependencies]
python = ">=3.11,<3.15"
colorama = "*"
pytest = "*"
pytest-asyncio = "*"
zenoh = ">=1.7.1,<2"
